name: Build CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout 
      uses: actions/checkout@v2
    - name: Use node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: build
      run: |
        cd blog
        npm install
        npm run precompile
        npm run build --if-present
      env:
        CI: true
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist    