name: Build CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout 
      uses: actions/checkout@v2
    - name: Use node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: build
      run: |
        npm install
        npm run precompile
        npm run build --if-present
      env:
        CI: true
    - name: deploy
      env:
        DEPLOY_SSH_PRIVATE_KEY: ${{ secrets.deploy_ssh }}
        DEPLOY_HOST: ${{ secrets.deploy_host }}
      run: |
        eval `ssh-agent -s`
        ssh-add <(echo "$DEPLOY_SSH_PRIVATE_KEY")
        ssh-add -l
        ssh -vv -o "StrictHostKeyChecking=no" anorwell@$DEPLOY_HOST 'echo hello'
        rsync -rv ./dist/* anorwell@$DEPLOY_HOST:/www/
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist